#!/usr/bin/env sh

echo '🔎 Linting...'
pnpm exec biome lint --write ./src ||
(
  echo '❌ Linting failed'
  false;
)

echo '🎨 Formatting...'
pnpm exec biome format --write ./src ||
(
  echo '❌ Formatting failed'
  false;
)

echo '✅ Linting and Formatting passed'
